/**
 * ⚠️ LEGACY CODE — READ ONLY
 *
 * STATUS: FROZEN
 * EFFECTIVE: 2026-01-31
 *
 * DO NOT EDIT THIS FILE.
 * Migrate logic to /server/src instead.
 *
 * @architecture legacy
 * @migration-target /server/src/features/<domain>
 */

const express = require('express');
const router = express.Router();
const auditController = require('../controllers/auditController');
const requireAuth = require('../middleware/auth');

// Get audit logs
router.get('/:companyId', requireAuth, auditController.getCompanyAuditLogs);

// Export logs
router.get('/:companyId/export', requireAuth, auditController.exportAuditLogs);

module.exports = router;
