/**
 * ⚠️ LEGACY CODE — READ ONLY
 *
 * STATUS: FROZEN
 * EFFECTIVE: 2026-01-31
 *
 * DO NOT EDIT THIS FILE.
 * Migrate logic to /server/src instead.
 *
 * @architecture legacy
 * @migration-target /server/src/features/<domain>
 */

// server/routes/search.js
const express = require("express");
const router = express.Router();
const requireAuth = require("../middleware/auth");
const searchCtrl = require("../controllers/searchController");

// Universal search endpoint
router.get("/universal", requireAuth, searchCtrl.universalSearch);
router.get("/contacts", requireAuth, searchCtrl.searchContactsHandler);

module.exports = router;
